In [16]:
from pathlib import Path

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.preprocessing import StandardScaler

In [17]:
PROJECT_ROOT = Path.cwd()

DATA_DIR = PROJECT_ROOT / "../data" / "processed"
DATA_DIR.mkdir(parents=True, exist_ok=True)

print(f"Project root: {PROJECT_ROOT}")
print(f"Processed data directory: {DATA_DIR}")

Project root: /Users/tolulopesoetan/Desktop/pl_prediction_model/notebooks
Processed data directory: /Users/tolulopesoetan/Desktop/pl_prediction_model/notebooks/../data/processed

In [18]:
# load dataset
urls = {
    "2122": "https://www.football-data.co.uk/mmz4281/2122/E0.csv",
    "2223": "https://www.football-data.co.uk/mmz4281/2223/E0.csv",
    "2324": "https://www.football-data.co.uk/mmz4281/2324/E0.csv",
    "2425": "https://www.football-data.co.uk/mmz4281/2425/E0.csv",
}

frames = []

for season, url in urls.items():
    df = pd.read_csv(url)
    df["season"] = season
    frames.append(df)

raw = pd.concat(frames, ignore_index=True)

print("Raw shape:", raw.shape)
print("\nColumns:")
print(raw.columns.tolist())

Raw shape: (1520, 133)

Columns:
['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'season', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA']

In [19]:
raw[
    [
        "Date",
        "HomeTeam",
        "AwayTeam",
        "FTR",
        "FTHG",
        "FTAG",
        "HTHG",
        "HTAG",
        "B365H",
        "B365D",
        "B365A",
    ]
].head(10)

,Date,HomeTeam,AwayTeam,FTR,FTHG,FTAG,HTHG,HTAG,B365H,B365D,B365A
0,13/08/2021,Brentford,Arsenal,H,2,0,1,0,4.00,3.40,1.95
1,14/08/2021,Man United,Leeds,H,5,1,1,0,1.53,4.50,5.75
2,14/08/2021,Burnley,Brighton,A,1,2,1,0,3.10,3.10,2.45
3,14/08/2021,Chelsea,Crystal Palace,H,3,0,2,0,1.25,5.75,13.00
4,14/08/2021,Everton,Southampton,H,3,1,0,1,1.90,3.50,4.00
5,14/08/2021,Leicester,Wolves,H,1,0,1,0,1.66,3.80,5.25
6,14/08/2021,Watford,Aston Villa,H,3,2,2,0,3.10,3.20,2.37
7,14/08/2021,Norwich,Liverpool,A,0,3,0,1,9.00,5.75,1.30
8,15/08/2021,Newcastle,West Ham,A,2,4,2,1,3.20,3.50,2.20
9,15/08/2021,Tottenham,Man City,H,1,0,0,0,5.50,4.20,1.60

In [20]:
# check for missing values
cols_to_check = [
    "FTR",
    "FTHG",
    "FTAG",
    "HTHG",
    "HTAG",
    "B365H",
    "B365D",
    "B365A",
    "HS",
    "AS",
    "HST",
    "AST",
]

raw[cols_to_check].isnull().sum()

FTR      0
FTHG     0
FTAG     0
HTHG     0
HTAG     0
B365H    0
B365D    0
B365A    0
HS       0
AS       0
HST      0
AST      0
dtype: int64

In [21]:
print("Full-time result distribution:")
print(raw["FTR"].value_counts(dropna=False))

print("\nRows per season:")
print(raw.groupby("season")["FTR"].count())

Full-time result distribution:
FTR
H    677
A    493
D    350
Name: count, dtype: int64

Rows per season:
season
2122    380
2223    380
2324    380
2425    380
Name: FTR, dtype: int64

In [22]:
# clean rows and parse dates

raw["Date"] = pd.to_datetime(raw["Date"], dayfirst=True, errors="coerce")

required_cols = [
    "Date",
    "HomeTeam",
    "AwayTeam",
    "FTR",
    "FTHG",
    "FTAG",
    "HTHG",
    "HTAG",
    "B365H",
    "B365D",
    "B365A",
]

raw = (
    raw.dropna(subset=required_cols)
       .sort_values("Date")
       .reset_index(drop=True)
       .copy()
)

print("Cleaned shape:", raw.shape)
print("Date range:", raw["Date"].min(), "to", raw["Date"].max())

Cleaned shape: (1520, 133)
Date range: 2021-08-13 00:00:00 to 2025-05-25 00:00:00

In [23]:
# build bookmaker market probabilities

raw["mkt_h"] = 1 / raw["B365H"]
raw["mkt_d"] = 1 / raw["B365D"]
raw["mkt_a"] = 1 / raw["B365A"]

margin = raw["mkt_h"] + raw["mkt_d"] + raw["mkt_a"]

raw["market_home_prob"] = raw["mkt_h"] / margin
raw["market_draw_prob"] = raw["mkt_d"] / margin
raw["market_away_prob"] = raw["mkt_a"] / margin

#raw

raw["market_prediction"] = (
    raw[["market_home_prob", "market_draw_prob", "market_away_prob"]]
    .idxmax(axis=1)
    .map(
        {
            "market_home_prob": "H",
            "market_draw_prob": "D",
            "market_away_prob": "A",
        }
    )
)

market_acc = (raw["market_prediction"] == raw["FTR"]).mean()

print(f"Market baseline accuracy: {market_acc:.3f}")
print("\nMarket prediction counts:")
print(raw["market_prediction"].value_counts())

Market baseline accuracy: 0.569

Market prediction counts:
market_prediction
H    959
A    561
Name: count, dtype: int64

In [24]:
raw[
    [
        "Date",
        "HomeTeam",
        "AwayTeam",
        "FTR",
        "market_home_prob",
        "market_draw_prob",
        "market_away_prob",
        "market_prediction",
        "season",
    ]
].head(10)

,Date,HomeTeam,AwayTeam,FTR,market_home_prob,market_draw_prob,market_away_prob,market_prediction,season
0,2021-08-13,Brentford,Arsenal,H,0.236532,0.278273,0.485194,A,2122
1,2021-08-14,Man United,Leeds,H,0.622631,0.211695,0.165674,H,2122
2,2021-08-14,Burnley,Brighton,A,0.306250,0.306250,0.387500,A,2122
3,2021-08-14,Chelsea,Crystal Palace,H,0.761299,0.165500,0.073202,H,2122
4,2021-08-14,Everton,Southampton,H,0.495575,0.269027,0.235398,H,2122
5,2021-08-14,Leicester,Wolves,H,0.570440,0.249192,0.180368,H,2122
6,2021-08-14,Watford,Aston Villa,H,0.305179,0.295642,0.399179,A,2122
7,2021-08-14,Norwich,Liverpool,A,0.105393,0.164963,0.729644,A,2122
8,2021-08-15,Newcastle,West Ham,A,0.296839,0.271396,0.431766,A,2122
9,2021-08-15,Tottenham,Man City,H,0.174003,0.227861,0.598136,A,2122

In [25]:
# save processed data

output_path = DATA_DIR / "raw_matches.csv"
raw.to_csv(output_path, index=False)

print(f"Saved cleaned matches to: {output_path}")

Saved cleaned matches to: /Users/tolulopesoetan/Desktop/pl_prediction_model/notebooks/../data/processed/raw_matches.csv

In [26]:
# create rolling form creatures

def compute_rolling_features(df, n_matches=5):
    """
    Create rolling form features that use past matches to calculate average points, goals scored, 
    goals conceded and recent home team win rate vs this opponent
    """
    df = df.copy().sort_values("Date").reset_index(drop=True)

    team_history = {}
    rows = []

    def get_form(history, n=n_matches):
        """
        Calculate recent form statistics from a team's previous matches. 
        Returns average points, goals scored, goals conceded, and number of games over the last n matches. 
        If there is no history yet, returns None values.
        """
        recent = history[-n:]
        if len(recent) == 0:
            return {
                "form_pts": None,
                "goals_for": None,
                "goals_against": None,
                "n_games": 0,
            }

        return {
            "form_pts": sum(match["pts"] for match in recent) / len(recent),
            "goals_for": sum(match["gf"] for match in recent) / len(recent),
            "goals_against": sum(match["ga"] for match in recent) / len(recent),
            "n_games": len(recent),
        }

    def get_h2h_home_winrate(home_team, away_team, home_history, n=n_matches):
        """
        Calculate the recent head-to-head home win rate for the home team against the away team, 
        based only on the home team's stored history. 
        If no recent head-to-head history exists, return 0.33 as a neutral default.
        """
        default_h2h_home_winrate = (raw["FTR"] == "H").mean()
        recent_h2h = [match for match in home_history if match["opponent"] == away_team][-n:]
        if len(recent_h2h) == 0:
            return default_h2h_home_winrate
        wins = sum(1 for match in recent_h2h if match["pts"] == 3)
        return wins / len(recent_h2h)

    for _, row in df.iterrows():
        home = row["HomeTeam"]
        away = row["AwayTeam"]
        date = row["Date"]

        home_history = team_history.get(home, [])
        away_history = team_history.get(away, [])

        home_form = get_form(home_history)
        away_form = get_form(away_history)
        h2h_home_winrate = get_h2h_home_winrate(home, away, home_history)

        rows.append(
            {
                "Date": date,
                "HomeTeam": home,
                "AwayTeam": away,
                "FTR": row["FTR"],
                "FTHG": row["FTHG"],
                "FTAG": row["FTAG"],
                "HTHG": row["HTHG"],
                "HTAG": row["HTAG"],
                "home_form_pts": home_form["form_pts"],
                "home_goals_for": home_form["goals_for"],
                "home_goals_against": home_form["goals_against"],
                "away_form_pts": away_form["form_pts"],
                "away_goals_for": away_form["goals_for"],
                "away_goals_against": away_form["goals_against"],
                "h2h_home_winrate": h2h_home_winrate,
                "market_home_prob": row["market_home_prob"],
                "market_draw_prob": row["market_draw_prob"],
                "market_away_prob": row["market_away_prob"],
                "season": row["season"],
            }
        )

        home_pts = 3 if row["FTR"] == "H" else 1 if row["FTR"] == "D" else 0
        away_pts = 3 if row["FTR"] == "A" else 1 if row["FTR"] == "D" else 0

        if home not in team_history:
            team_history[home] = []
        if away not in team_history:
            team_history[away] = []

        team_history[home].append(
            {
                "date": date,
                "pts": home_pts,
                "gf": row["FTHG"],
                "ga": row["FTAG"],
                "opponent": away,
            }
        )

        team_history[away].append(
            {
                "date": date,
                "pts": away_pts,
                "gf": row["FTAG"],
                "ga": row["FTHG"],
                "opponent": home,
            }
        )

    return pd.DataFrame(rows)

In [27]:
features_basic = compute_rolling_features(raw)

features_basic = (
    features_basic.dropna(subset=["home_form_pts", "away_form_pts"])
                  .reset_index(drop=True)
                  .copy()
)

features_basic["market_prediction"] = (
    features_basic[["market_home_prob", "market_draw_prob", "market_away_prob"]]
    .idxmax(axis=1)
    .map(
        {
            "market_home_prob": "H",
            "market_draw_prob": "D",
            "market_away_prob": "A",
        }
    )
)

print("Engineered feature shape:", features_basic.shape)
print("\nRows per season after feature engineering:")
print(features_basic.groupby("season").size())

Engineered feature shape: (1504, 20)

Rows per season after feature engineering:
season
2122    370
2223    377
2324    378
2425    379
dtype: int64

In [28]:
features_basic[
    [
        "Date",
        "HomeTeam",
        "AwayTeam",
        "FTR",
        "home_form_pts",
        "home_goals_for",
        "home_goals_against",
        "away_form_pts",
        "away_goals_for",
        "away_goals_against",
        "h2h_home_winrate",
        "market_home_prob",
        "market_draw_prob",
        "market_away_prob",
        "season",
    ]
].head(10)

,Date,HomeTeam,AwayTeam,FTR,home_form_pts,home_goals_for,home_goals_against,away_form_pts,away_goals_for,away_goals_against,h2h_home_winrate,market_home_prob,market_draw_prob,market_away_prob,season
0,2021-08-21,Crystal Palace,Brentford,D,0.0,0.0,3.0,3.0,2.0,0.0,0.445395,0.372387,0.296746,0.330867,2122
1,2021-08-21,Liverpool,Burnley,H,3.0,3.0,0.0,0.0,1.0,2.0,0.445395,0.801216,0.126058,0.072726,2122
2,2021-08-21,Aston Villa,Newcastle,H,0.0,2.0,3.0,0.0,2.0,4.0,0.445395,0.527508,0.253204,0.219288,2122
3,2021-08-21,Man City,Norwich,H,0.0,0.0,1.0,0.0,0.0,3.0,0.445395,0.877408,0.086146,0.036446,2122
4,2021-08-21,Brighton,Watford,H,3.0,2.0,1.0,3.0,3.0,2.0,0.445395,0.561367,0.272664,0.165969,2122
5,2021-08-21,Leeds,Everton,D,0.0,1.0,5.0,3.0,3.0,1.0,0.445395,0.402081,0.280274,0.317644,2122
6,2021-08-22,Southampton,Man United,D,0.0,1.0,3.0,3.0,5.0,1.0,0.445395,0.172037,0.225286,0.602677,2122
7,2021-08-22,Wolves,Tottenham,A,0.0,0.0,1.0,3.0,1.0,0.0,0.445395,0.297468,0.297468,0.405063,2122
8,2021-08-22,Arsenal,Chelsea,A,0.0,0.0,2.0,3.0,3.0,0.0,0.445395,0.198875,0.251908,0.549218,2122
9,2021-08-23,West Ham,Leicester,H,3.0,4.0,2.0,3.0,1.0,0.0,0.445395,0.381188,0.272277,0.346535,2122

In [29]:
# logistic regression to check the new features

FEATURES_BASIC = [
    "home_form_pts",
    "home_goals_for",
    "home_goals_against",
    "away_form_pts",
    "away_goals_for",
    "away_goals_against",
    "h2h_home_winrate",
    "market_home_prob",
    "market_draw_prob",
]

train = features_basic[features_basic["season"].isin(["2122","2223", "2324"])].copy()
test = features_basic[features_basic["season"] == "2425"].copy()

X_train = train[FEATURES_BASIC]
y_train = train["FTR"]
X_test = test[FEATURES_BASIC]
y_test = test["FTR"]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(class_weight="balanced", max_iter=1000)
lr.fit(X_train_scaled, y_train)

lr_preds = lr.predict(X_test_scaled)

print(f"Market baseline accuracy: {accuracy_score(y_test, test['market_prediction']):.3f}")
print(f"LR accuracy:             {accuracy_score(y_test, lr_preds):.3f}")
print(f"LR weighted F1:          {f1_score(y_test, lr_preds, average='weighted'):.3f}")
print()
print(classification_report(y_test, lr_preds, zero_division=0))

Market baseline accuracy: 0.538
LR accuracy:             0.488
LR weighted F1:          0.489

              precision    recall  f1-score   support

           A       0.56      0.52      0.54       131
           D       0.25      0.26      0.25        93
           H       0.58      0.60      0.59       155

    accuracy                           0.49       379
   macro avg       0.46      0.46      0.46       379
weighted avg       0.49      0.49      0.49       379

In [30]:
features_output_path = DATA_DIR / "features_basic.csv"
features_basic.to_csv(features_output_path, index=False)

print(f"Saved engineered features to: {features_output_path}")

Saved engineered features to: /Users/tolulopesoetan/Desktop/pl_prediction_model/notebooks/../data/processed/features_basic.csv